<?php

/**
 * @file
 * Contains client_url.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function client_url_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the care module.
    case 'help.page.client_url':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides Client Url field.') . '</p>';
      return $output;

    default:             
  }
}
